name: Everkey
options:
  deploymentTarget:
    macOS: "12.0"

packages:
  EverkeyEngine:
    path: EverkeyEngine

targets:
  Everkey:
    type: application
    platform: macOS
    sources:
      - Everkey
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.everkey.app
        INFOPLIST_FILE: Everkey/Info.plist
        CODE_SIGN_ENTITLEMENTS: Everkey/Everkey.entitlements
        CODE_SIGN_STYLE: Automatic
        MACOSX_DEPLOYMENT_TARGET: "12.0"
        SWIFT_VERSION: "5.7"
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
    dependencies:
      - package: EverkeyEngine
        product: EverkeyEngine
